### ISSUE TITLE
firecloud help execute and error

### ISSUE THREAD

**Issue by jasonkimMGB** [broadinstitute/firecloud-cli#1]
first git clone from repo...
and run ./install.sh
and run  export PATH=~/.firecloud-cli/ubin:$PATH
and run firecloud --help
but error [ImportError: No module named oauth2client.client]

--error--
$ firecloud help
Traceback (most recent call last):
  File "/root/.firecloud-cli/ubin/firecloud", line 11, in <module>
    load_entry_point('firecloudcli==0.1.0', 'console_scripts', 'firecloud')()
  File "/root/.firecloud-cli/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/root/.firecloud-cli/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/root/.firecloud-cli/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/root/.firecloud-cli/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/root/.firecloud-cli/venv/local/lib/python2.7/site-packages/firecloudcli-0.1.0-py2.7.egg/firecloudcli/main.py", line 1, in <module>
    import methods_repo
  File "/root/.firecloud-cli/venv/local/lib/python2.7/site-packages/firecloudcli-0.1.0-py2.7.egg/firecloudcli/methods_repo.py", line 27, in <module>
    from oauth2client.client import GoogleCredentials
ImportError: No module named oauth2client.client

--python version
$ python -V
Python 2.7.12

--ubuntu version
$ uname -ra
Linux 90a4b29d1c71 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

any suggestions?

**Comment by abaumann** [comment]
Hi Jason,

This project is very old and no longer valid - where did you learn about it from?  What you probably want is this:
https://github.com/broadinstitute/fiss
